#include "taskforge/infrastructure.hpp"
#include <stdexcept>
#include <sstream>
#include <iomanip>
#include <cstdlib>
#include <cstring>
namespace taskforge {
static void check(PGconn* c){if(PQstatus(c)!=CONNECTION_OK) throw std::runtime_error(PQerrorMessage(c));}
PgStore::PgStore(const DbConfig& cfg){conn_=PQconnectdb(cfg.conninfo.c_str());check(conn_);}
PgStore::~PgStore(){if(conn_)PQfinish(conn_);}
static std::string esc(PGconn* c,const std::string& s){char* x=PQescapeLiteral(c,s.c_str(),s.size());if(!x)throw std::runtime_error(PQerrorMessage(c));std::string r=x;PQfreemem(x);return r;}
std::string PgStore::create_job(const Job& j){std::scoped_lock l(mutex_);std::string q="INSERT INTO jobs(id,execution_id,name,priority,status,payload,timeout_ms,attempt,max_attempts,worker_id) VALUES('"+j.id+"','"+j.execution_id+"',"+esc(conn_,j.name)+",'"+to_string(j.priority)+"','QUEUED',"+esc(conn_,j.payload)+","+std::to_string(j.timeout.count())+",0,"+std::to_string(j.max_attempts)+",NULL) RETURNING id";PGresult*r=PQexec(conn_,q.c_str());if(PQresultStatus(r)!=PGRES_TUPLES_OK){auto e=PQerrorMessage(conn_);PQclear(r);throw std::runtime_error(e);}std::string id=PQgetvalue(r,0,0);PQclear(r);return id;}
std::optional<Job> PgStore::get_job(const std::string&id){std::scoped_lock l(mutex_);std::string q="SELECT id,execution_id,name,priority,status,payload,timeout_ms,attempt,max_attempts,COALESCE(worker_id,'') FROM jobs WHERE id='"+id+"'";PGresult*r=PQexec(conn_,q.c_str());if(PQresultStatus(r)!=PGRES_TUPLES_OK){auto e=PQerrorMessage(conn_);PQclear(r);throw std::runtime_error(e);}if(PQntuples(r)==0){PQclear(r);return std::nullopt;}Job j;j.id=PQgetvalue(r,0,0);j.execution_id=PQgetvalue(r,0,1);j.name=PQgetvalue(r,0,2);auto p=std::string(PQgetvalue(r,0,3));j.priority=p=="HIGH"?Priority::High:p=="LOW"?Priority::Low:Priority::Normal;auto st=std::string(PQgetvalue(r,0,4));if(st=="SUCCEEDED")j.status=JobStatus::Succeeded;else if(st=="RUNNING")j.status=JobStatus::Running;else if(st=="FAILED")j.status=JobStatus::Failed;else if(st=="RETRYING")j.status=JobStatus::Retrying;else if(st=="DEAD_LETTER")j.status=JobStatus::DeadLetter;else if(st=="CANCELLED")j.status=JobStatus::Cancelled;else j.status=JobStatus::Queued;j.payload=PQgetvalue(r,0,5);j.timeout=std::chrono::milliseconds(std::stoll(PQgetvalue(r,0,6)));j.attempt=std::stoul(PQgetvalue(r,0,7));j.max_attempts=std::stoul(PQgetvalue(r,0,8));j.worker_id=PQgetvalue(r,0,9);PQclear(r);return j;}
std::vector<Job> PgStore::list_jobs(int limit){std::scoped_lock l(mutex_);std::string q="SELECT id FROM jobs ORDER BY created_at DESC LIMIT "+std::to_string(std::max(1,std::min(limit,1000)));PGresult*r=PQexec(conn_,q.c_str());if(PQresultStatus(r)!=PGRES_TUPLES_OK){auto e=PQerrorMessage(conn_);PQclear(r);throw std::runtime_error(e);}std::vector<Job> out;for(int i=0;i<PQntuples(r);++i){auto j=get_job(PQgetvalue(r,i,0));if(j)out.push_back(*j);}PQclear(r);return out;}
bool PgStore::update_status(const std::string&id,JobStatus st,const std::string&w){std::scoped_lock l(mutex_);std::string q="UPDATE jobs SET status='"+to_string(st)+"',worker_id="+(w.empty()?"NULL":esc(conn_,w)) +",updated_at=now() WHERE id='"+id+"'";PGresult*r=PQexec(conn_,q.c_str());bool ok=PQresultStatus(r)==PGRES_COMMAND_OK;PQclear(r);return ok;}
bool PgStore::record_attempt(const Job&j,const std::string&w,const std::string&s,const std::string&e){std::scoped_lock l(mutex_);std::string q="INSERT INTO job_attempts(job_id,execution_id,attempt_number,worker_id,status,started_at,finished_at,error_message) VALUES('"+j.id+"','"+j.execution_id+"',"+std::to_string(j.attempt)+","+esc(conn_,w)+","+esc(conn_,s)+",now(),now(),"+(e.empty()?"NULL":esc(conn_,e))+") ON CONFLICT DO NOTHING";PGresult*r=PQexec(conn_,q.c_str());bool ok=PQresultStatus(r)==PGRES_COMMAND_OK;PQclear(r);return ok;}
RedisClient::RedisClient(std::string h,uint16_t p):socket_(io_),host_(std::move(h)),port_(p){}
std::string RedisClient::command(const std::vector<std::string>&a){std::scoped_lock l(mutex_);if(!socket_.is_open()){socket_.connect({boost::asio::ip::make_address(host_),port_});}std::ostringstream q;q<<"*"<<a.size()<<"\r\n";for(auto&s:a)q<<"$"<<s.size()<<"\r\n"<<s<<"\r\n";boost::asio::write(socket_,boost::asio::buffer(q.str()));boost::asio::streambuf b;boost::asio::read_until(socket_,b,"\r\n");std::istream in(&b);std::string line;std::getline(in,line);if(!line.empty()&&line.back()=='\r')line.pop_back();return line;}
void RedisClient::setex(const std::string&k,int ttl,const std::string&v){command({"SETEX",k,std::to_string(ttl),v});} bool RedisClient::exists(const std::string&k){return command({"EXISTS",k})==":1";}
NatsClient::NatsClient(std::string h,uint16_t p):socket_(io_),host_(std::move(h)),port_(p){connect();} NatsClient::~NatsClient(){boost::system::error_code e;socket_.close(e);}
void NatsClient::connect(){socket_.connect({boost::asio::ip::make_address(host_),port_});boost::asio::streambuf b;boost::asio::read_until(socket_,b,"\r\n");std::string line;std::istream in(&b);std::getline(in,line);std::string info="CONNECT {\"verbose\":false,\"pedantic\":false,\"lang\":\"C++23\",\"version\":\"1.0\"}\r\nPING\r\n";boost::asio::write(socket_,boost::asio::buffer(info));}
void NatsClient::publish(const std::string&s,const std::string&p){std::scoped_lock l(mutex_);std::string x="PUB "+s+" "+std::to_string(p.size())+"\r\n"+p+"\r\n";boost::asio::write(socket_,boost::asio::buffer(x));}
std::string NatsClient::read_line(){boost::asio::streambuf b;boost::asio::read_until(socket_,b,"\r\n");std::istream in(&b);std::string x;std::getline(in,x);if(!x.empty()&&x.back()=='\r')x.pop_back();return x;}
std::optional<std::pair<std::string,std::string>> NatsClient::next(const std::string&subject){std::scoped_lock l(mutex_);if(!subscribed_){std::string sub="SUB "+subject+" taskforge-worker\r\n";boost::asio::write(socket_,boost::asio::buffer(sub));subscribed_=true;}for(;;){auto line=read_line();if(line.rfind("MSG ",0)!=0)continue;std::istringstream i(line);std::string m,sid,reply;size_t n;i>>m>>sid>>reply>>n;std::vector<char> p(n+2);boost::asio::read(socket_,boost::asio::buffer(p));return std::make_pair(sid,std::string(p.data(),n));}}
}
